### ISSUE TITLE
achieve concurrency in azure sync

### ISSUE THREAD

**Issue by ajoytech** [Azure/azure-mobile-apps-ios-client#167]
How do we achieve concurrency with azure sync. If I want to do pull, push etc operations from a background managedobjectcontext and read and display data from another main managedobjectcontext?

**Comment by julianiaccopucci** [comment]
I'm facing the same issue. As per Core Data documentation, to make an async operation with Core Data we'd need a concurrent MOC, and then call the performBlock: or performBlockAndWait method of the MOC instance. The library is not calling those methods, so how can we achieve concurrency with the current implementation?

**Comment by MatkovIvan** [comment]
Hi @ajoytech,

Thanks for getting in touch.
`MSCoreDataStore` can be initialized by private queue context to do operations in the background.
The following documents may be useful for you:
- [Core Data Concurrency](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CoreData/Concurrency.html)
- [Enable offline syncing with iOS mobile apps](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-get-started-offline-data)

@julianiaccopucci The library uses those methods and since it open-source you can verify this yourself in [MSCoreDataStore.m](https://github.com/Azure/azure-mobile-apps-ios-client/blob/3.4.0/sdk/src/MSCoreDataStore.m)

Best,
Ivan

**Comment by elamalani** [comment]
@ajoytech @julianiaccopucci Were you able to achieve concurrency by following the documents shared by @MatkovIvan? Please let us know if the solution worked our for you so that we can close the ticket. Thanks!

**Comment by ajoytech** [comment]
@elamalani I haven't implemented the approach yet so can't confirm the result.  I will come back with the result when I implement this. For now please update the ticket state as per policy.
Thanks.

**Comment by elamalani** [comment]
@ajoytech Thanks!
