### ISSUE TITLE
Sync Errors: Cancel/Keep/Modify Validate Item Id vs Operation Item Id

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps-ios-client#18]
Review if the helper methods on operation error should be more defensive and error out if the item attempting to be upserted/deleted via these calls does not match the original item id the operation was for.  (Technically since Cancel\* are in the wild, this is a breaking change)

**Comment by elamalani** [comment]
@phvannor Thanks for using Azure Mobile Apps. This issue seems to be older than 2 years, so I will close it for now but feel free to reach out in case you have questions. 

Please look at the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps). Thanks!
