### ISSUE TITLE
Can't call custom API successfully from iOS client

### ISSUE THREAD

**Issue by krisragh** [Azure/azure-mobile-apps-ios-client#55]
When I try to invoke a custom API, I get the error below.

I created an Easy API, allowed anonymous access for all methods, and created a really basic Node script. 

The error is: "ERROR Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1103 "The item provided was not valid." UserInfo={NSLocalizedDescription=The item provided was not valid.}"
 

Here is a screenshot that shows my custom API (sendEmail.js) defined via Easy APIs on the server side + iOS code on the client side. 

<img width="662" alt="screen shot 2016-03-01 at 11 55 13 am" src="https://cloud.githubusercontent.com/assets/1638063/13447239/b900c7e8-dfce-11e5-9f2b-49d6c52f7a05.png">

If I hit this via the web at https://phooey.azurewebsites.net/api/sendEmail or via Postman, the GET call works fine. But I can't get it to work via Objective-C code.

**Comment by phvannor** [comment]
The error is most likely due to the fact that you are passing a NSString for the body parameter that is not a valid JSON object.  If you want to send a string body, you must use the invokeApi:Data:... instead, this one assumes body will be a JSON payload.  (Also you shouldn't really send a body on a GET request)

**Comment by shrishrirang** [comment]
Thanks @phvannor!
