### ISSUE TITLE
Support Auth token refresh logic

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-ios-client#62]
Per http://cgillum.tech/2016/03/07/app-service-token-store/

We need to support client.refresh() that will refresh the auth tokens. A basic implementation that calls the refresh with X-ZUMO-AUTH and sets the mobile service auth token before resolving/rejecting the token would be enough to start.

**Comment by egrimmius** [comment]
Is there a way to call the GET api, "/.auth/refresh", mentioned in:

http://cgillum.tech/2016/03/07/app-service-token-store/ 

via the current release of the SDK, at least manually?  I've tried by calling MSClient's invokeAPI like this:

        .invokeAPI("/.auth/refresh", body: nil, HTTPMethod: "GET", parameters: nil, headers: 2.0.0, completion: ({
            (result : AnyObject?, response : NSHTTPURLResponse?, error: NSError?) -> Void in

However, it returns a 404 error - "Cannot GET /api/.auth/refresh".

Thanks.

**Comment by dhei** [comment]
@egrimmius The Refresh token API it's not done yet. In the meanwhile, you can manually invoke "/.auth/refresh" endpoint with proper headers. Do you have a valid x-zumo-auth header in your request?

**Comment by egrimmius** [comment]
@dhei I don't know if I have a valid x-zumo-auth header in my request.  I just was calling .invokeAPI from MSClient.  Do I need to manually write my own NSURLRequest, etc. myself then?  I haven't tried that yet.

**Comment by dhei** [comment]
@egrimmius MSClient InvokeAPI does send a valid [x-zumo-auth](https://github.com/Azure/azure-mobile-apps-ios-client/blob/f0c4b229dcab29cb5d75c1cb7a201c81c862a8df/sdk/src/MSClientConnection.m#L20) header when you're already logged in. You don't need any special header to call refresh endpoint. You can use InvokeAPI instead of writing your own USURLRequest.

Can I ask which identity provider (MicrosoftAccount / Azure ActiveDirectory / Google?) is involved here with refresh? Did you login with offline access permission before refresh? If the user is not logged in with proper offline access permission/scope from the identity provider, you may be 404 error when calling refresh endpoint because refresh token is not present in the App Service backend. The blog post mentioned above gives a decent explanation on how to login with offline access permission: http://cgillum.tech/2016/03/07/app-service-token-store/

**Comment by egrimmius** [comment]
@dhei I'm using Azure AD, and the ADAL pod with it.  ADAL handles the token caching and refreshing for Azure AD.  Once logged in there, I login via MSClient's .loginWithProvider.  I'm only trying to be able to refresh MSClient's currentUser's mobileServiceAuthenticationToken.  

I tried using MSClient InvokeAPI to GET /.auth/me or GET /.auth/refresh, and both came back with the 404 errors.  I since tried it using Alamofire, and while that succeeds for GET /.auth/me, it fails for GET /.auth/refresh.

**Comment by adrianhall** [comment]
@egrimmius If you are doing refresh with ADAL, then use the ADAL refresh logic - when you refresh the token and get a new token, send it to Mobile Apps via MSClient's .loginWithProvider.

The refresh logic we are adding does this for server flow type scenarios.  You can already do refresh logic on the client flow without specific logic in the SDK.

**Comment by egrimmius** [comment]
@adrianhall OK, that sounds much easier.  If my token from ADAL doesn't need refreshing, the mobile Service Authentication Token won't need to be refreshed either?

**Comment by adrianhall** [comment]
Not necessarily - any token can be expired on different schedules, so it depends.  The difference is that the mobile service auth token is a "behind the scenes"  auth token with no user interaction in your case, so refreshing it is as simple as re-using the ADAL token to log in again.

**Comment by adrianhall** [comment]
In case it wasn't clear - what I'm proposing is an interim solution until we get to refresh in the library and is specific to your case (client flow where the auth provider provides refresh logic already).

**Comment by egrimmius** [comment]
@adrianhall Thanks for the clarification.  For now, I'll react to 401s by logging in again via the user's AD token via ADAL.

**Comment by dhei** [comment]
This feature is released in v[3.2.0](https://github.com/Azure/azure-mobile-apps-ios-client/releases/tag/3.2.0)
