### ISSUE TITLE
Fix travis test failures on Mac

### ISSUE THREAD

**Issue by shrishrirang** [Azure/azure-mobile-apps-ios-client#82]
Refer: https://travis-ci.org/Azure/azure-mobile-apps-ios-client/builds/141531683

**Comment by damienpontifex** [comment]
@shrishrirang I may have fixed the issues with the mac tests, but now failing on a test at https://github.com/Azure/azure-mobile-apps-ios-client/blob/master/sdk/test/MSSyncTableTests.m#L1539

Trying to wrap my head around where/why it's now failing, but are you certain this should asset equal 1 rather than 2 considering the previous test for cancellation at point 4 has count 2? I wouldn't have thought this count would go down in this instance from step 4 to 5?

**Comment by shrishrirang** [comment]
Step 5 isn't really the next step after step 4. Step 1, 2, 3 and 4 are guaranteed to run one after the other, while step 5 can run anytime because it is run in a different thread. This is causing a race condition - one thread which is pulling records and another thread which cancels the operation.

https://github.com/Azure/azure-mobile-apps-ios-client/commit/410a171e672e5d187d975ae5a368d5f6dcf46005 was aimed to fix this, but looks like this bug wasn't fixed due to oversight. The fix will be to change https://github.com/Azure/azure-mobile-apps-ios-client/blob/master/sdk/test/MSSyncTableTests.m#L1800-L1807 to perform the cancellation first and then leave the dispatch group. 

The push test does this correctly: https://github.com/Azure/azure-mobile-apps-ios-client/blob/master/sdk/test/MSSyncTableTests.m#L1377-L1383

**Comment by elamalani** [comment]
Closing this issue as it's over a year old and we are not making any changes related to this issue.
